### ISSUE TITLE
Warning: No provider for "framework:effroi"

### ISSUE THREAD

**Issue by moneypenny** [francejs/effroi#12]
> Running "karma:unit" (karma) task
Warning: No provider for "framework:effroi"! (Resolving: framework:effroi) Use --force to continue.

I ran `npm install karma-effroi --save-dev`, it's in my package.json, my karma.conf.coffee has `frameworks: ['jasmine', 'effroi']`. Is there somewhere else I need to reference effroi to get it available in my tests?

**Comment by Aaronius** [comment]
Thanks @Yvem. You save me some time.
