### ISSUE TITLE
Support JQuery selectors

### ISSUE THREAD

**Issue by pcw216** [francejs/effroi#13]
It would be great if effroi handled jquery results seamlessly.
For example:
```
effroi.mouse.click($("li:contains('My Item')"))
```
This would also make it possible to provide meaningful exception/error messages that mention the element selector.

If you give the :+1: I'll work on a pull request.

**Comment by nfroidure** [comment]
Not sure this is a good idea to rely on JQuery, why not just wrap this lib in another one?  We'd be glad to add it on the README file.
